/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["LoginRequestBody"];
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        /** @description アクセストークン（JWT）を HttpOnly Cookie にセット */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginSuccessResponse"];
                    };
                };
                /** @description ログイン失敗（ユーザーが存在しないか、パスワードが正しくない） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログアウト成功 */
                204: {
                    headers: {
                        /** @description アクセストークン（JWT）を Cookie から削除 */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認可チェック */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 認可成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthCheckResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー情報取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー情報取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserInfoResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 月次の資産情報取得 */
        get: {
            parameters: {
                query: {
                    /** @description 基準日（YYYY-MM-DD形式） */
                    baseDate: components["parameters"]["BaseDateParameter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 月次の資産情報取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetsInfoResponse"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 年次の資産情報取得 */
        get: {
            parameters: {
                query: {
                    /** @description 基準日（YYYY-MM-DD形式） */
                    baseDate: components["parameters"]["BaseDateParameter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 年次の資産情報取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetsInfoResponse"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 共通のエラーレスポンス */
        ErrorResponse: {
            /**
             * @description エラーコード
             * @enum {string}
             */
            code: "INVALID_CREDENTIALS" | "INVALID_ACCESS_TOKEN" | "INVALID_RESPONSE_DATA" | "NOT_FOUND" | "INTERNAL_SERVER_ERROR";
            /**
             * @description エラーメッセージ
             * @enum {string}
             */
            message: "Invalid Credentials" | "Invalid Access Token" | "Invalid Response Data" | "Not Found" | "Internal Server Error";
        };
        /** @description ログイン成功時のレスポンス */
        LoginSuccessResponse: {
            /** @description ユーザー名 */
            name: string;
        };
        /** @description 認可成功時のレスポンス */
        AuthCheckResponse: {
            /**
             * @description 認可成功を表す真偽値
             * @enum {boolean}
             */
            ok: true;
        };
        /** @description ユーザー情報取得レスポンス */
        UserInfoResponse: {
            /** @description ユーザーID */
            id: string;
            /** @description ユーザー名 */
            name: string;
        };
        /** @description 月次・年次の資産情報レスポンス */
        AssetsInfoResponse: {
            /** @description 年月（YYYY-MM形式） */
            yearMonth: string;
            /** @description その年月の合計資産額 */
            totalAssets: number;
            /** @description カテゴリー別の資産情報 */
            assetsByCategories: components["schemas"]["AssetsCategoryInfo"][];
        };
        /** @description カテゴリー別資産情報 */
        AssetsCategoryInfo: {
            /**
             * @description 資産カテゴリー
             * @enum {string}
             */
            category: "現金" | "債券" | "国内株式" | "海外株式" | "投資信託" | "現物不動産" | "REIT" | "コモディティ" | "暗号資産" | "年金" | "保険" | "その他";
            /** @description カテゴリーの資産額 */
            amount: number;
            /** @description 全体に占める割合（%） */
            rate: number;
        };
    };
    responses: {
        /** @description 認可チェック失敗 */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 基準日（YYYY-MM-DD形式） */
        BaseDateParameter: string;
    };
    requestBodies: {
        LoginRequestBody: {
            content: {
                "application/json": {
                    /** @description ユーザー名 */
                    name: string;
                    /** @description パスワード */
                    password: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
