/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /**
                     * @description ユーザー名
                     * @example Lillie
                     */
                    name: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ユーザーID */
                            id: string;
                            /** @description ユーザー名 */
                            name: string;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description エラーコード
             * @enum {string}
             */
            code: "INVALID_CREDENTIALS" | "INVALID_TOKEN" | "INVALID_RESPONSE_DATA" | "NOT_FOUND" | "INTERNAL_SERVER_ERROR";
            /**
             * @description エラーメッセージ
             * @enum {string}
             */
            message: "Invalid Credentials" | "Invalid Token" | "Invalid Response Data" | "Not Found" | "Internal Server Error";
        };
    };
    responses: {
        /** @description ユーザーが存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
